version: "3.9"

services:
  api:
    container_name: api
    image: api_express_entrega_sprint_3
    build: .
    ports:
      - 3001:3001
    environment:
      - DB_USER=th
      - DB_PASSWORD=1234
      - DB_HOST=db
      - DB=products_management
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=th
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=products_management
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U th -d products_management"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
